Q1= input("What is your favorite animal?\n")
Q2= input("Why do you like them?\n")
Q3= input("Where do they live?\n")
Q4= input("What is one fun fact about them?\n")
print ("your favorite animal is the"+" "+ Q1 +" "+"you like them because"+" "+ Q2 +" "+"they live in"+" "+ Q3 +" "+ "1 fun fact is"+" " + Q4 )