Q1= int(input("give a number greater than 7\n"))
print(Q1 > 7)
Q2= int(input("enter a number equal to 10\n "))
print(Q2 == 10)
Q3= int(input("enter a number greater than or equal to 23 \n"))
print(Q3 >= 23)
Q4= int(input("enter a number less than or equal to 35 \n"))
print(Q4 <= 35)
Q5= int(input("enter a number less than 100 \n "))
print( Q5 < 100)
Q6= int(input(" enter a number not equal to 20\n"))
print(Q6 != 20)